# netlify.toml

[build]
  base    = "my-web"  # Adjust this to your project's base directory if needed
  publish = "build"
  command = "CI=false react-scripts build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
